include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Recommended rules
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps

analyzer:
  errors:
    # Turn off the required TODO comment rule
    todo: ignore
  exclude:
    - build/**
    - .dart_tool/**
    - .idea/**
    - .vscode/**